Repository softeerbootcamp-3rd/Team1-driving-today, pull requests merged in 2024-02, with the labels that each got.

#29 [FE] feat: button component
  frontend/src/components/button/README.md
  frontend/src/components/button/button.tsx
  frontend/src/components/button/index.ts
Labels: enhancement, FE

#24 [FE] feat: reset css, font
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/button/README.md
  frontend/src/components/button/button.tsx
  frontend/src/components/button/index.ts
  frontend/src/index.css
Labels: enhancement, FE

#34 refactor : 폴더구조변경
  backend/driving-today/src/main/java/com/drivingtoday/domain/.gitkeep
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/Academy.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/Student.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/SwaggerConfig.java
  backend/driving-today/src/main/java/com/drivingtoday/service/.gitkeep
Labels: BE

#25 [BE] feat : reservation 생성 기능 완료
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/Academy.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/Student.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentRepository.java
  backend/driving-today/src/test/java/com/drivingtoday/ReservationTest/ReservationControllerTest.java
Labels: BE

#35 [BE] bugfix : student 필드 중복문제 해결
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
Labels: BE

#41 ci : workflow 파일 원복
  .github/workflows/deploy_main.yml
  .github/workflows/deploy_test.yml
  backend/driving-today/src/main/resources/.gitkeep
Labels: bug

#39 [FE] feat: chip component
  frontend/src/components/chip/README.md
  frontend/src/components/chip/chip.tsx
  frontend/src/components/chip/index.ts
Labels: FE

#42 [FE] feat: path alias with vite
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: enhancement, FE

#38 [FE] feat: sidebar icon component
  frontend/src/assets/icons/building.svg
  frontend/src/assets/icons/call.svg
  frontend/src/assets/icons/date.svg
  frontend/src/assets/icons/duration.svg
  frontend/src/assets/icons/history.svg
  frontend/src/assets/icons/home.svg
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/location.svg
  frontend/src/assets/icons/make_reservation.svg
  frontend/src/assets/icons/marker.svg
  frontend/src/assets/icons/message.svg
  frontend/src/assets/icons/payments.svg
  frontend/src/assets/icons/reservation.svg
  frontend/src/assets/icons/time.svg
  frontend/src/assets/react.svg
  frontend/src/components/icon/README.md
  frontend/src/components/icon/icon.tsx
  frontend/src/components/icon/index.ts
  frontend/src/components/sidebarIcon/README.md
  frontend/src/components/sidebarIcon/index.ts
  frontend/src/components/sidebarIcon/sidebarIcon.tsx
Labels: FE

#52 bugfix: failed to resolve path
  frontend/vite.config.ts
Labels: bug, FE

#43 [BE] feat : my reservations listing
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/Academy.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/Student.java
Labels: BE

#57 [BE] refactor : 56 hotfix로 불필요한 파일 삭제하여 github action 정상작동하게함
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationService.java
Labels: BE

#53 [FE] feat: divider component
  frontend/src/components/divider/README.md
  frontend/src/components/divider/divider.tsx
  frontend/src/components/divider/index.ts
Labels: enhancement, FE

#46 [BE] feat : 리뷰 등록 api
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/Academy.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/Student.java
  backend/driving-today/src/main/resources/data.sql
  backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewAddServiceTest.java
Labels: BE

#67 Hotfix/66 review
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
Labels: BE

#64 [FE] feat: checkbox component
  frontend/src/components/checkbox/README.md
  frontend/src/components/checkbox/checkbox.tsx
  frontend/src/components/checkbox/index.ts
Labels: enhancement, FE

#55 [BE] feat : 특정 강사 상세 정보 출력 API 개발
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AcademyInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorDetailResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/ReviewDetail.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/resources/data.sql
  backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorFindServiceTest.java
Labels: BE

#63 [BE] feat : 특정 강사에 대한 리뷰 조회 API 개발
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewFindRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
  backend/driving-today/src/main/resources/data.sql
  backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewFindServiceTest.java
Labels: BE

#60 [FE] feat: sidebar component
  frontend/src/components/button/button.tsx
  frontend/src/components/button/index.ts
  frontend/src/components/icon/index.ts
  frontend/src/components/sidebar/README.md
  frontend/src/components/sidebar/index.ts
  frontend/src/components/sidebar/sidebar.tsx
  frontend/src/components/sidebarIcon/README.md
  frontend/src/components/sidebarIcon/index.ts
  frontend/src/components/sidebarIcon/sidebarIcon.tsx
  frontend/src/index.css
Labels: enhancement, FE

#59 [FE] feat: star+rating component
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/star.svg
  frontend/src/assets/icons/star_empty.svg
  frontend/src/assets/icons/star_half.svg
  frontend/src/components/rating/README.md
  frontend/src/components/rating/index.ts
  frontend/src/components/rating/rating.tsx
Labels: FE

#48 [BE] feat : 예약 가능한 강사 목록 보여주기
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AvailableInstructorInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AvailableInstructorsRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/DbConfig.java
  backend/driving-today/src/main/resources/.gitkeep
  backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorFindServiceTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorRepositoryTest.java
Labels: BE

#84 [BE] feat : 학생 정보 조회 API 개발
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/dto/StudentInfo.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/student/StudentFindServiceTest.java
Labels: BE

#69 [BE] feat : 예약 취소 API 작성
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/dto/.gitkeep
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/dto/AcademyInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/.gitkeep
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorDetailResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationDeleteService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationDetailResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewDetail.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/dto/StudentInfo.java
Labels: BE

#89 [BE] feat : 강사가 본인한테 들어온 예약 확인하는 API
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationDeleteService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
Labels: BE

#83 [FE] feat: header 컴포넌트 작성
  frontend/src/assets/icons/arrow_back.svg
  frontend/src/assets/icons/index.ts
  frontend/src/components/header/README.md
  frontend/src/components/header/header.tsx
  frontend/src/components/header/index.ts
Labels: enhancement, FE

#88 [FE] feat: 폴더구조 작성
  frontend/src/App.tsx
  frontend/src/pages/dashboard/page.tsx
  frontend/src/pages/history/page.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/login/page.tsx
  frontend/src/pages/page.tsx
  frontend/src/pages/purchase/page.tsx
  frontend/src/pages/schedule/page.tsx
Labels: feat, FE

#95 [FE] feat: card component
  frontend/src/components/card/README.md
  frontend/src/components/card/card.tsx
  frontend/src/components/card/index.ts
Labels: FE

#101 [FE] feat: useFetch hook
  frontend/src/hooks/use-fetch.ts
Labels: FE

#100 [FE] feat: search instructor form
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/icon/icon.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/schedule/page.tsx
  frontend/tsconfig.json
Labels: feat, FE

#107 [FE] hotfix: useFetch fix dependency
  frontend/src/hooks/use-fetch.ts
Labels: FE

#109 [BE] feat : 강사 평점 조회 기능 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AvailableInstructorInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorDetailResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/resources/data.sql
Labels: BE

#117 feat : 로그인/회원가입
  backend/driving-today/build.gradle
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/Student.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/constants/Authentication.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/constants/Role.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/exception/JwtErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/exception/JwtException.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/jwt/Jwt.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/jwt/JwtProvider.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebConfig.java
  backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java
  backend/driving-today/src/main/java/com/drivingtoday/global/s3/S3Config.java
  backend/driving-today/src/main/java/com/drivingtoday/global/s3/S3UploadService.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/TestController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserJoinController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserJoinService.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserLoginController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserLoginService.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/InstructorJoinRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/LoginRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/LoginResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/StudentJoinRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/exception/UserErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/exception/UserException.java
  backend/driving-today/src/main/resources/data.sql
Labels: BE

#118 [BE] feat : 예약 동시간대에 접수 못하게 막는 로직 구현
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationException.java
  backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep
Labels: BE

#122 feat : 리뷰 컨트롤러, 서비스에 로그인 로직 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/exception/ReviewErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/exception/ReviewException.java
  backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java
Labels: BE

#110 [FE] feat: search instructors page
  frontend/public/marker.png
  frontend/src/App.tsx
  frontend/src/components/card/card.tsx
  frontend/src/pages/schedule/page.tsx
  frontend/src/pages/search/components/index.ts
  frontend/src/pages/search/components/search-preview.tsx
  frontend/src/pages/search/data.ts
  frontend/src/pages/search/page.tsx
Labels: feat, FE

#113 [FE] feat: history page
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/index.ts
  frontend/src/components/card/card.tsx
  frontend/src/components/tab/tab.tsx
  frontend/src/hooks/use-fetch.ts
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/history/components/cardlist/index.ts
  frontend/src/pages/history/components/modal/index.ts
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/history/page.tsx
  frontend/src/utils/constants.ts
Labels: feat, FE

#125 [BE] feat : 예약 관련 API 수정
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationDeleteService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java
Labels: BE

#128 [BE] feat : Swagger 로그인 설정
  backend/driving-today/src/main/java/com/drivingtoday/global/config/SwaggerConfig.java
Labels: BE

#126 [FE] feat: update layout
  frontend/src/components/header/header.tsx
  frontend/src/components/sidebar/sidebar.tsx
Labels: FE

#133 [BE] feat : 리뷰 응답에 리뷰 작성자 사진 정보 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewDetail.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
Labels: BE

#123 [FE] feat: dashboard page
  frontend/src/assets/icons/arrow_forward.svg
  frontend/src/assets/icons/car.svg
  frontend/src/assets/icons/index.ts
  frontend/src/pages/dashboard/components/cardlist/cardlist.tsx
  frontend/src/pages/dashboard/components/myprofile-card/index.ts
  frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
  frontend/src/pages/dashboard/components/schedule-card/index.ts
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/dashboard/page.tsx
Labels: FE

#134 [BE] chore : cors allowHeaders 추가
  backend/driving-today/src/main/java/com/drivingtoday/global/config/CorsConfig.java
Labels: BE

#137 feat: purchase page markup
  frontend/src/pages/purchase/page.tsx
  frontend/src/pages/search/page.tsx
Labels: feat, FE

#144 [BE] feat : 예약 리스트 응답에 예정/완료 여부 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationInstructorResponse.java
  backend/driving-today/src/main/resources/data.sql
Labels: BE

#138 [FE] feat: auth
  frontend/src/App.tsx
  frontend/src/hooks/use-api-call.ts
  frontend/src/pages/dashboard/components/cardlist/cardlist.tsx
  frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/login/page.tsx
  frontend/src/utils/api.ts
  frontend/src/utils/session.ts
Labels: FE

#147 [BE] feat : 미래 예약, 과거 예약 구분해서 조회할 수 있도록 API 수정
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/resources/data.sql
Labels: BE

#149 [BE] feat : signup 포스트맨 안되던거 해결 완료, chat with jwt
  backend/driving-today/build.gradle
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoom.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketConfig.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketHandShakeInterceptor.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserJoinController.java
Labels: BE

#153 [BE] feat : reservation add edit
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoom.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoomRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/SessionService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationErrorCode.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketHandShakeInterceptor.java
Labels: BE

#132 [FE] feat: infinite scroll
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/hooks/use-intersection-observer.ts
Labels: feat, FE

#157 hotfix: LocalDateTime이 응답메시지에서 배열로 보이는 문제 해결
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationInstructorResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationStudentResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java
Labels: bug, BE

#160 [BE] feat : 테스트용 데이터 수정
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/resources/data.sql
Labels: BE

#156 [BE] feat : 예약 추가 수정 및 채팅 refactor
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoom.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoomRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketConfig.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketHandShakeInterceptor.java
Labels: BE

#167 [BE] feat : chat api 강사가 본인에게 온 메시지들 톡방 리스트화 API
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoomRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
Labels: BE

#169 feat: setting vitest
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: feat, FE

#142 [FE] feat: 연수 예약 form 상태 validate 구현
  frontend/src/App.tsx
  frontend/src/pages/purchase/loader.ts
  frontend/src/pages/purchase/page.tsx
  frontend/src/pages/schedule/hooks/index.ts
  frontend/src/pages/schedule/hooks/use-current-position.ts
  frontend/src/pages/schedule/page.tsx
  frontend/src/pages/schedule/types.ts
  frontend/src/pages/schedule/utils/index.ts
  frontend/src/pages/schedule/utils/validate-form-data.ts
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/data.ts
  frontend/src/pages/search/loader.ts
  frontend/src/pages/search/page.tsx
  frontend/src/utils/object-to-qs.ts
  frontend/src/utils/validate.ts
Labels: feat, FE

#154 feat: 마커 애니메이션, 강사리스트/리뷰(무한스크롤), 강사 상세 API 연동
  frontend/public/marker.png
  frontend/public/marker.svg
  frontend/src/components/loading/index.ts
  frontend/src/components/loading/loading.tsx
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/index.css
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/page.tsx
  frontend/src/pages/search/types.ts
Labels: feat, FE

#179 feat: 연수생용, 강사용 api에 각각 /student, /instructor 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
Labels: BE

#172 [FE] feat: implement useSuspendedApiCall
  frontend/src/hooks/use-api-call.ts
  frontend/src/utils/api.ts
Labels: FE

#165 [FE] feat: calendar component
  frontend/src/pages/dashboard/components/calendar/calendar.tsx
  frontend/src/pages/dashboard/components/calendar/components.tsx
  frontend/src/pages/dashboard/components/calendar/date-picker.tsx
  frontend/src/pages/dashboard/components/calendar/index.ts
  frontend/src/pages/dashboard/components/calendar/reducer.ts
  frontend/src/pages/dashboard/components/calendar/utils.ts
Labels: FE

#175 [FE] feat: 연수 예약 API 연동
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/components/flex/flex.tsx
  frontend/src/components/flex/index.ts
  frontend/src/components/typography/index.ts
  frontend/src/components/typography/typography.tsx
  frontend/src/pages/purchase/loader.ts
  frontend/src/pages/purchase/page.tsx
  frontend/src/pages/purchase/success/page.tsx
Labels: feat, FE

#187 [BE] feat : mongodb chat
  backend/driving-today/build.gradle
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfoConcise.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfoDetail.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
Labels: BE

#198 feat : api refactoring
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/dto/SliceResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserJoinController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserLoginController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserRegisterController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserRegisterService.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/InstructorRegisterRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/global/user/dto/StudentRegisterRequest.java
Labels: BE

#190 [FE] feat: implement portal component and useModal hook
  frontend/src/components/portal/index.ts
  frontend/src/components/portal/portal.tsx
  frontend/src/hooks/use-modal.ts
  frontend/src/main.tsx
  frontend/src/pages/components/chat-modal/chat-modal.tsx
  frontend/src/pages/components/chat-modal/index.ts
  frontend/src/pages/components/index.ts
  frontend/src/providers/chat-modal-provider.tsx
  frontend/src/providers/index.ts
Labels: feat, FE

#201 feat : 로그인한 연수생, 강사 정보 반환 API
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
Labels: BE

#207 [BE] feat : Redisson을 이용한 동시성 문제 해결
  backend/driving-today/build.gradle
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationLockFacade.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationRequest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/reservation/ReservationConcurrencyTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewAddServiceTest.java
Labels: BE

#213 [BE] bugfix : JwtFilter alloList 수정
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
Labels: BE

#196 fix: useInfiniteFetch 타입 수정
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/page.tsx
Labels: feat, FE

#220 [BE] feat : 로드밸런서의 상태 확인용 api
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
  backend/driving-today/src/main/java/com/drivingtoday/global/config/HealthCheckController.java
Labels: BE

#177 [FE] feat: save session to browser
  frontend/src/utils/session.ts
Labels: FE

#226 [BE] feat : 학원 검색 api
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/dto/AcademySearchResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
Labels: BE

#236 [BE] feat : Review 엔티티 연관 관계 추가
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
Labels: BE

#237 [BE] hotfix : 테이블 구조 변경을 위한 커밋
  backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep
Labels: BE

#239 [BE] refactor : chat message response 구조 개선
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
Labels: BE

#218 [FE] feat: search page date picker component
  frontend/src/pages/dashboard/components/calendar/components.tsx
  frontend/src/pages/schedule/page.tsx
Labels: FE

#210 [FE] feat: 로그인/회원가입 기능 구현
  frontend/public/clapping-hands.svg
  frontend/src/App.tsx
  frontend/src/assets/icons/avatar.svg
  frontend/src/assets/icons/index.ts
  frontend/src/hooks/use-escape-keydown.ts
  frontend/src/index.css
  frontend/src/pages/components/auth-modal/components/image-field.tsx
  frontend/src/pages/components/auth-modal/components/index.ts
  frontend/src/pages/components/auth-modal/components/text-field.tsx
  frontend/src/pages/components/auth-modal/components/textarea-field.tsx
  frontend/src/pages/components/auth-modal/index.ts
  frontend/src/pages/components/auth-modal/login-modal.tsx
  frontend/src/pages/components/auth-modal/register-modal.tsx
  frontend/src/pages/components/auth-modal/styles.tsx
  frontend/src/pages/components/index.ts
  frontend/src/pages/login/page.tsx
  frontend/src/pages/page.tsx
  frontend/src/utils/session.ts
Labels: feat, FE

#217 [FE] feat: useInfiniteFetch error handling + type error fix
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/page.tsx
Labels: FE, improve

#241 [BE] hotfix : 인프라 작업에 따른 cicd 세팅
  backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep
Labels: BE

#195 [FE] feat: dashboard page api
  frontend/src/components/card/card.tsx
  frontend/src/hooks/use-scroll-to.ts
  frontend/src/pages/dashboard/components/calendar/calendar.tsx
  frontend/src/pages/dashboard/components/calendar/reducer.ts
  frontend/src/pages/dashboard/components/cardlist/cardlist.tsx
  frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/dashboard/page.tsx
  frontend/src/pages/purchase/page.tsx
  frontend/src/pages/purchase/success/page.tsx
Labels: FE

#184 [FE] feat: use api in history page
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/history/page.tsx
  frontend/src/types/reservation.ts
Labels: FE

#245 [FE] fix(vite.config.ts): `build.assetInlineLimit` setting to zero
  frontend/vite.config.ts
Labels: feat, FE

#246 [BE] feat : 지난 예약 리스트에 리뷰 작성 여부 포함
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationStudentResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewRequest.java
Labels: BE

#228 [FE] wip: scroll based animation
  frontend/public/car.png
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/logo_head.svg
  frontend/src/assets/icons/logo_rest.svg
  frontend/src/pages/components/landing/first-stage.tsx
  frontend/src/pages/components/landing/index.ts
  frontend/src/pages/components/landing/landing.tsx
  frontend/src/pages/components/landing/sample-wheel.tsx
  frontend/src/pages/components/landing/second-stage.tsx
  frontend/src/pages/components/landing/third-stage.tsx
  frontend/src/pages/page.tsx
  frontend/src/providers/scroll-animation-provider.tsx
  frontend/src/utils/animation.ts
Labels: feat, FE

#240 [FE] feat: ChatRoom 컴포넌트 작성(socket 연결)
  frontend/src/App.tsx
  frontend/src/assets/icons/index.ts
  frontend/src/assets/icons/paper_airplane.svg
  frontend/src/hooks/use-chat-socket.ts
  frontend/src/hooks/use-enter-keypress.ts
  frontend/src/pages/components/auth-modal/login-modal.tsx
  frontend/src/pages/components/auth-modal/register-modal.tsx
  frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
  frontend/src/pages/components/chat-modal/chat-home/index.ts
  frontend/src/pages/components/chat-modal/chat-modal.tsx
  frontend/src/pages/components/chat-modal/chat-room/chat-item.tsx
  frontend/src/pages/components/chat-modal/chat-room/chat-room-layout.tsx
  frontend/src/pages/components/chat-modal/chat-room/chat-room.tsx
  frontend/src/pages/components/chat-modal/chat-room/index.ts
  frontend/src/pages/components/chat-modal/chat-room/instructor-chat-room.tsx
  frontend/src/pages/components/chat-modal/chat-room/student-chat-room.tsx
  frontend/src/pages/components/chat-modal/chat-room/styles.tsx
  frontend/src/pages/components/chat-modal/index.ts
  frontend/src/pages/layout.tsx
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/page.tsx
  frontend/src/utils/time.ts
Labels: feat, FE

#257 [BE] feat : 이름으로 학원 찾는 쿼리 include 방식으로 변경
  backend/driving-today/src/main/java/com/drivingtoday/domain/academy/AcademyRepository.java
Labels: BE

#266 [BE] refactor : academy instructor fetch join
  backend/driving-today/build.gradle
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoomRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/SessionService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/dto/ChatRoomInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoom.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/Instructor.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AvailableInstructorsRequest.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorDetailResponse.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/ReviewDetail.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/exception/InstructorException.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/global/aop/Timer.java
  backend/driving-today/src/main/java/com/drivingtoday/global/aop/TimerAop.java
Labels: BE

#271 [FE] feat: errorboundary and fallback
  frontend/public/error.png
  frontend/src/App.tsx
  frontend/src/components/card/card.tsx
  frontend/src/components/skeleton/index.ts
  frontend/src/components/skeleton/skeleton.tsx
  frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
  frontend/src/pages/components/chat-modal/chat-room/chat-room.tsx
  frontend/src/pages/components/chat-modal/chat-room/instructor-chat-room.tsx
  frontend/src/pages/components/chat-modal/chat-room/student-chat-room.tsx
  frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/not-found.tsx
  frontend/src/pages/search/components/detail-dialog.tsx
  frontend/src/pages/search/components/detail-dialog/detail-dialog.tsx
  frontend/src/pages/search/components/detail-dialog/index.ts
  frontend/src/pages/search/components/detail-dialog/instructor-detail.tsx
  frontend/src/pages/search/components/detail-dialog/types.ts
Labels: feat, FE, refactor

#269 [FE] fix: fix student info card in chat modal home
  frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
Labels: invalid, FE

#256 [FE] feat: change instructor search mechanism
  frontend/src/App.tsx
  frontend/src/components/card/card.tsx
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/hooks/use-intersection-observer.ts
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/purchase/loader.ts
  frontend/src/pages/reservation/page.tsx
  frontend/src/pages/reservation/schedule/hooks/index.ts
  frontend/src/pages/reservation/schedule/hooks/use-current-position.ts
  frontend/src/pages/reservation/schedule/page.tsx
  frontend/src/pages/reservation/schedule/types.ts
  frontend/src/pages/reservation/schedule/utils/index.ts
  frontend/src/pages/reservation/schedule/utils/validate-form-data.ts
  frontend/src/pages/reservation/search/components/detail-dialog.tsx
  frontend/src/pages/reservation/search/components/index.ts
  frontend/src/pages/reservation/search/components/search-preview.tsx
  frontend/src/pages/reservation/search/data.ts
  frontend/src/pages/reservation/search/loader.ts
  frontend/src/pages/reservation/search/page.tsx
  frontend/src/pages/reservation/search/types.ts
  frontend/src/pages/search/page.tsx
  frontend/src/providers/map-context.tsx
Labels: feat, FE, refactor

#267 [FE] feat: enhance landing page
  frontend/src/App.tsx
  frontend/src/pages/components/landing/first-stage.tsx
  frontend/src/pages/components/landing/landing.tsx
  frontend/src/pages/components/landing/second-stage.tsx
  frontend/src/pages/components/landing/third-stage.tsx
  frontend/src/pages/page.tsx
  frontend/src/providers/scroll-animation-provider.tsx
Labels: FE, improve

#262 [FE] feat: add gc to api cache
  frontend/src/hooks/use-api-call.ts
  frontend/src/utils/api.ts
Labels: FE, improve

#247 [FE] feat: register login validation
  frontend/src/pages/components/auth-modal/components/academy-field.tsx
  frontend/src/pages/components/auth-modal/components/index.ts
  frontend/src/pages/components/auth-modal/components/text-field.tsx
  frontend/src/pages/components/auth-modal/components/textarea-field.tsx
  frontend/src/pages/components/auth-modal/register-modal.tsx
  frontend/src/pages/components/auth-modal/styles.tsx
Labels: FE, improve

#252 [FE] feat: distinguish reviewed reservations from history
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/history/components/modal/modal.tsx
  frontend/src/pages/history/page.tsx
  frontend/src/types/reservation.ts
Labels: FE

#254 [FE] feat: deploy-web workflow
  .github/workflows/deploy-web.yml
  frontend/src/hooks/use-api-call.ts
  frontend/src/hooks/use-infinite-fetch.ts
  frontend/src/pages/components/auth-modal/components/textarea-field.tsx
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/reservation/search/components/detail-dialog.tsx
  frontend/src/pages/reservation/search/components/detail-dialog/detail-dialog.tsx
  frontend/src/pages/reservation/search/components/detail-dialog/index.ts
  frontend/src/pages/reservation/search/components/detail-dialog/instructor-detail.tsx
  frontend/src/pages/reservation/search/components/detail-dialog/types.ts
  frontend/src/pages/reservation/search/page.tsx
Labels: feat, FE

#276 feat: meta data
  frontend/index.html
  frontend/public/open-graph.png
Labels: feat, FE

#272 [BE] feat : 회원가입시 사진 입력을 안하면 기본이미지로 세팅
  backend/driving-today/src/main/java/com/drivingtoday/global/user/UserRegisterService.java
Labels: BE

#279 docs: README 작성
  README.md
  backend/driving-today/example.application.yml
  docs/강사-대시보드.png
  docs/강사-지난연수내역.png
  docs/강사-채팅.png
  docs/인프라-및-아키텍처.png
  docs/학생-대시보드-예약완료.png
  docs/학생-대시보드.png
  docs/학생-연수예약1.png
  docs/학생-연수예약2.png
  docs/학생-연수예약3.png
  docs/학생-연수예약4.png
  docs/학생-예약내역1.png
  docs/학생-예약내역2.png
  docs/학생-예약내역3.png
  docs/학생-채팅.png
  frontend/.env.example
Labels: documentation

#283 [BE] refactor : 리뷰 리스트 조회 쿼리 성능 개선
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewFindService.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
  backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
  backend/driving-today/src/main/java/com/drivingtoday/global/dto/SliceResponse.java
Labels: BE

#282 [FE] feat: landing page message
  frontend/public/chat.png
  frontend/public/review.png
  frontend/src/pages/components/landing/first-stage.tsx
  frontend/src/pages/components/landing/second-stage.tsx
  frontend/src/providers/scroll-animation-provider.tsx
Labels: FE, improve

#287 [FE] feat: lazy load image
  frontend/src/components/card/card.tsx
  frontend/src/components/lazy-image/index.ts
  frontend/src/components/lazy-image/lazy-image.tsx
  frontend/src/components/logo/logo.tsx
  frontend/src/pages/components/auth-modal/register-modal.tsx
  frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
  frontend/src/pages/components/chat-modal/chat-room/styles.tsx
  frontend/src/pages/components/landing/second-stage.tsx
  frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
  frontend/src/pages/reservation/page.tsx
  frontend/src/pages/reservation/search/components/detail-dialog/instructor-detail.tsx
Labels: FE, improve

#292 [FE] fix: resolve token error
  frontend/src/App.tsx
  frontend/src/components/sidebar/sidebar.tsx
  frontend/src/hooks/use-chat-socket.ts
  frontend/src/hooks/use-fetch.ts
  frontend/src/pages/components/auth-modal/components/academy-field.tsx
  frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
  frontend/src/pages/components/chat-modal/chat-room/chat-room.tsx
  frontend/src/pages/components/landing/second-stage.tsx
  frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
  frontend/src/pages/history/components/cardlist/cardlist.tsx
  frontend/src/pages/layout.tsx
  frontend/src/pages/login/page.tsx
  frontend/src/pages/page.tsx
  frontend/src/pages/reservation/search/components/detail-dialog/instructor-detail.tsx
  frontend/src/pages/reservation/search/page.tsx
  frontend/src/utils/api.ts
  frontend/src/utils/constants.ts
  frontend/src/utils/is-error-instance.ts
  frontend/src/utils/session.ts
Labels: feat, FE

#293 [BE] test : entity별 테스트 코드 수정
  backend/driving-today/src/main/resources/data.sql
  backend/driving-today/src/test/java/com/drivingtoday/ReservationTest/ReservationControllerTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorFindServiceTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorRepositoryTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewFindServiceTest.java
  backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewRepositoryTest.java
Labels: BE
